id: 30c8784674e84e2e8073d47ad26de7df
initial_creation_type: ocr
source_metadata:
  volumes:
    a3a6b957dd4a44a9b69d2073fc990131:
      base_file: v087.txt
      image_group_id: I1PD95933
      title: ''
      total_pages: 1560
      volume_number: 88
